### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by RPetrov**
1. Added .gitignore. You shouldn't commit "/build" and some other directories.
2. Some renames
3. Closures in UserDataPageActivity

### CODE REVIEW

**Comment by RPetrov** [comment]
And add @RPetrov rpetrov as Collaborator
settings -> Collaborators -> add Collaborator

**Review by tatisled — COMMENTED** [review]
I believe I have a gitignore file in my primary repo, I'll check. Why should I ignore build directory?

**Review by tatisled — APPROVED** [review]

**Review by tatisled — APPROVED** [review]
These classes will probably be renamed again (FirstPage is higher likely)

**Comment by RPetrov** [comment]
Because of http://alblue.bandlem.com/2011/03/git-tip-of-week-ignoring-build-output.html

Shortly, build output depends on source code and it is just temporary files.

**Pull request merged**
